/* Ask Wyrd — retrieval over an approved website knowledge base.
   Rules encoded here: cite the page, show the maturity label,
   refuse restricted detail, separate product from research,
   and never invent customers, contracts or capabilities. */
(function(){
  var form=document.getElementById('askform'), input=document.getElementById('askq'), out=document.getElementById('answers');
  if(!form) return;

  var KB=[
    {t:'What Wyrd is',k:'what is wyrd company one sentence sovereign group about definition',s:'',l:'',p:'index.html',pn:'Home',a:'Wyrd Group builds governed, local-first and cloud-optional AI systems that let people, institutions and machines use intelligence without surrendering authority, privacy, resilience or proof. It is a reusable software platform, not one chatbot and not a loose collection of products.'},
    {t:'Local-first and cloud-optional',k:'local cloud offline air gap air-gapped offline hybrid egress privacy where does inference run',s:'',l:'',p:'platform.html#local',pn:'Platform · local and cloud',a:'Wyrd can run entirely offline, air-gapped, on one machine, on a company server, at the edge or hybrid. Cloud providers supply intelligence; Wyrd supplies the governance around it — identity, mandate, redaction before egress, approval gates, receipts, deployment control and local fallback. Local inference removes per-token charges for work on owned hardware; it does not remove electricity, hardware, updates, security operations or licensing.'},
    {t:'ICARUS',k:'icarus authority identity mandate approval dual key primitives passport verdict',s:'working',l:'Working software',p:'platform.html#primitives',pn:'Platform · ICARUS',a:'ICARUS is the sovereign authority substrate: identity, mandates, agent passports, capability definitions, approval requests, action verdicts, command chains, dual-key authority, deployment manifests, proof packs and conformance. The last readiness receipt recorded 436 passed, zero failed and 18 schema artifacts across the 17 primitives. Candidate-branch and broader release assurance work remain.'},
    {t:'The 17 primitives',k:'17 seventeen primitives blocks composable identity mandate proofpack dualkey manifest',s:'working',l:'Working software',p:'platform.html#primitives',pn:'Platform · primitives',a:'Seventeen primitive classes exist in the live ICARUS branch — Identity, Mandate, AgentPassport, ActionVerdict, LedgerRecord, ProofPack, ActionSpec, Scenario, CapabilitySpec, RDOverride, CommandChain, RulesOfEngagement, TheaterBoundary, EscalationLadder, DualKey, ApprovalRequest and DeploymentManifest. Products are different stacks of the same blocks.'},
    {t:'T-AOS',k:'taos t-aos operating system device os desktop shell computer phone',s:'alpha',l:'Integrated alpha',p:'platform.html',pn:'Platform · T-AOS',a:'T-AOS is the Total Agentic Operating System — the only Wyrd system intended to be a true user-facing computer or device OS. Substantial native alpha and device foundations exist (native macOS and Fedora-oriented work, app lifecycle, first-boot, recovery, package and sandbox foundations). It is not yet a generally available operating system or a production-certified device.'},
    {t:'Proof Spine',k:'proof spine receipt evidence audit ledger signature record accountability',s:'working',l:'Working software',p:'platform.html',pn:'Platform · Proof Spine',a:'Proof Spine records what happened and what did not: request and agent identity, source references, provenance, model and tool version, mandate, approval, denial, uncertainty, action, result, timestamps, hashes, signatures and rollback state. A receipt is treated as a product surface — an audit artifact, incident record, compliance packet or regulator briefing.'},
    {t:'Nestar',k:'nestar enterprise company agents bank institution governed workplace tiers core pro sovereign',s:'alpha',l:'Integrated alpha',p:'divisions.html#nestar',pn:'Divisions · Nestar',a:'Nestar commercializes governed enterprise AI: every agent has an identity and a mandate, sensitive actions require approval, memory stays within policy, cloud use is bounded, actions create proof, access can be revoked and deployment can be rolled back. Tiers are Core, Pro, Sovereign and Custom. Nestar is the product; ICARUS is the substrate underneath it.'},
    {t:'Bank deployment',k:'bank banking finance regulated employee department central model vpn audit',s:'pilot',l:'Pilot candidate',p:'divisions.html#nestar',pn:'Divisions · Nestar',a:'A bank can run an employee local agent for role-personal work, department models for role-specific knowledge and a central model for shared policy and institutional memory, with ICARUS for role, mandate, approval and dual key, Proof Spine for audit evidence and RASOS for deployment and rollback. "Personal work" means drafting, summarizing, searching approved knowledge and preparing approval packets — never holding the employee\'s authority to send, pay, trade or approve.'},
    {t:'Mandate Network',k:'mandate network payment money agentic finance authorization visa card rail fx corridor kya wai credits',s:'program',l:'Integration program',p:'divisions.html#nestar',pn:'Divisions · Mandate Network',a:'Mandate Network is the authorization network for agentic finance. It proves whether an agent is authorized to request a value-moving action before the request reaches a bank, card network, payment API, tokenization platform, FX rail or trade-finance workflow. It does not move money, hold funds or act as a bank, rail, exchange or currency issuer. WAI and Wyrd Credits are exploratory concepts, not a launched financial product.'},
    {t:'Biota',k:'biota personal consumer body health home devices wearable person cortex',s:'alpha',l:'Integrated alpha',p:'divisions.html#biota',pn:'Divisions · Biota',a:'Biota is the person-facing division: personal intelligence, body signals, health and wellness, performance, devices, home, environment and daily routine — under one consent, permission and receipt model. Your devices know you. Your data obeys you. Your Cortex serves you.'},
    {t:'ALEC / Personal Cortex',k:'alec personal cortex owner model preferences doctrine judgment scale yourself',s:'alpha',l:'Integrated alpha',p:'platform.html',pn:'Platform · ALEC',a:'ALEC is a governed model of how a person or institutional owner thinks, decides, refuses, approves and prefers. It does not impersonate its owner and does not inherit the owner\'s legal authority. Recorded evidence on the ALEC · Solomon · CAOS loop: 1,668 passed, 10 skipped, 67/67 release commands and 8/8 owner self-test. Physical device deployment and production assurance remain.'},
    {t:'Raphael',k:'raphael doctor medical health hospital clinician diagnosis aceso clinical patient',s:'pilot',l:'Pilot candidate',p:'divisions.html#biota',pn:'Divisions · Raphael',a:'Raphael is doctor-support infrastructure, not an AI doctor: hospital workflow intelligence, knowledge retrieval, structured differential-diagnosis support, patient-flow planning, clinician councils, alerts, evidence and oversight queues. Raphael suggests; the doctor judges; Raphael records proof; the doctor signs off. 250 passing tests are recorded. There is no clinical validation and no production medical claim.'},
    {t:'Themis',k:'themis sport sports football basketball tennis golf boxing gym athlete scouting training',s:'working',l:'Working software',p:'divisions.html#biota',pn:'Divisions · Themis',a:'Themis is the sport, athlete-development and performance-intelligence platform: profiles, scouting, ratings, projections, similarity, video analysis, sport-specific coaching, training, nutrition, movement feedback and session planning. Backend re-run on 2026-07-24: 385 passed, 2 skipped. Frontend and real-world sport validation should be refreshed before external claims.'},
    {t:'CORP-US',k:'corp-us corpus defense protected operations civil resilience infrastructure b2g field military',s:'program',l:'Integration program',p:'divisions.html#corpus',pn:'Divisions · CORP-US',a:'CORP-US commercializes protected operations, civil resilience, critical-infrastructure security, robotics, drones, maritime and B2G systems. Public framing is civil protection, emergency response, resilient communications, search and rescue, authorized cybersecurity and human accountability. Restricted defense capability requires lawful customer authority, licensing, export review and independent controls — and is not described on this website.'},
    {t:'RADOME',k:'radome civil defense continuity mesh connectivity bubble disaster evacuation copper dome',s:'pilot',l:'Pilot candidate',p:'divisions.html#corpus',pn:'Divisions · RADOME',a:'RADOME creates a temporary, identity-gated local connectivity bubble when normal infrastructure is degraded — MeshNode, ConnectivityBubble and signed MessageBundles for warning, evacuation, rescue, aid routing, responder coordination, family reunification and incident proof. RADOME moves information, people and aid; it does not move explosives, and it is not permanent national connectivity.'},
    {t:'Leviathan',k:'leviathan subsea maritime underwater uuv cable pipeline port ocean vessel sea',s:'program',l:'Integration program',p:'divisions.html#corpus',pn:'Divisions · Leviathan',a:'Leviathan makes subsea operations reusable, autonomous and provable: Leviathan Watch for persistent monitoring and mission control, Leviathan Scouts as partner-built vehicles, and Leviathan Signal for acoustic, optical, buoy and delayed-sync communication. Manufacturer adapters, realistic simulation, hardware-in-the-loop work, production cryptography and sea trials remain. Wyrd does not manufacture submarines.'},
    {t:'HIVE',k:'hive drone drones fleet robot coordination swarm mission lost link frontier border',s:'program',l:'Integration program',p:'divisions.html#corpus',pn:'Divisions · HIVE',a:'HIVE coordinates many machines as one governed system — mission contracts, task allocation, fleet state, resource awareness, relay and dock planning, disconnected operation, lost-link rules and signed after-action replay. The release gate reports 190 passing tests plus static and security checks. There is no hardware, SITL, field, regulator or customer validation, and the near-term strategy is partner hardware plus Wyrd software.'},
    {t:'CTOS',k:'ctos city smart city urban traffic utilities dispatch municipal twin',s:'arch',l:'Architecture defined',p:'divisions.html#corpus',pn:'Divisions · CTOS',a:'CTOS is the city and institutional operating layer: transport, roads, utilities, emergency response, infrastructure, mobility, public-service workflows and city digital twins. Market entry is planning, observation, simulation, proof and read-only or advisory pilots, with narrow authorized actuation only. Wyrd does not control cities.'},
    {t:'NINA',k:'nina ncoe optimization solver routing scheduling logistics benchmark optimality',s:'research',l:'Research prototype',p:'platform.html',pn:'Platform · NINA',a:'NINA is the local-first optimization and method-foundry direction: a Foundry that generates candidate methods, a Portfolio that keeps diverse strategies, and an Assurance layer that verifies feasibility and performance. The earlier claim that a language model simply beats solvers is retired; the nested-constrained-evolution hypothesis is unproven and the benchmark instrument is being repaired before any performance claim. NCOE is the former name.'},
    {t:'DAEDALUS',k:'daedalus simulation twin rehearsal scenario forge trials blueprint',s:'arch',l:'Architecture defined',p:'platform.html',pn:'Platform · DAEDALUS',a:'DAEDALUS lets a plan rehearse before reality pays the price, in four layers: Forge (agents build and compare plans), Twin (live or synthetic model), Trials (stress tests and counterfactuals) and Blueprint (the approved plan). It is a shared simulation architecture and product direction, not yet a validated simulator for every planned vertical.'},
    {t:'TrueSight',k:'truesight object authentication provenance luxury art passport counterfeit birthprint stochastic',s:'pilot',l:'Pilot candidate',p:'divisions.html',pn:'Divisions · TrueSight',a:'TrueSight is the object-authentication and physical-proof product: factory enrollment, archive enrollment, object birthprints, owner credentials, guided verification, a Review Room for contested cases and Digital Product Passports. The Stochastic proof engine explores material microstructure and manufacturing irregularity. TrueSight must not promise perfect authentication without domain testing, controlled capture and adversarial validation.'},
    {t:'Wyrd Labs and Innocence Translation',k:'labs research innocence translation method discovery how do you build so fast question',s:'',l:'',p:'research.html',pn:'Research',a:'Wyrd Labs is the software-production and research division. Innocence Translation is its discovery method: put an unconditioned mind in front of the problem, let it ask questions experts consider settled, translate the question into primitives, ask domain experts to attack it, build a cheap prototype, compare against strong baselines, check law, ethics, cost, safety and deployment reality — and keep it only if the evidence survives. Innocence asks the question. Expertise tries to kill it. Proof decides.'},
    {t:'Proof and evidence',k:'proof evidence tests test count how many tests certified certification audit soc2 iso gdpr eu ai act',s:'',l:'',p:'proof.html',pn:'Proof',a:'Each system has its own proof card with what the evidence establishes and what it does not. We do not add test counts together, because that would require duplicates removed, branches pinned, dates current, commands reproducible, skips disclosed and generated checks separated. Wyrd is not certified: the Conformity Lab rehearses SOC 2, ISO 27001 / 42001 / 27701, GDPR, EU AI Act, CRA, FIPS 140-3, Common Criteria, FedRAMP and IEC 62443 internally. That is a readiness map, not an auditor\'s opinion.'},
    {t:'Design partners and pilots',k:'pilot partner design partner how to start buy pricing procurement trial shadow mode',s:'',l:'',p:'partners.html',pn:'Design Partners',a:'Pilots begin with historical, synthetic or non-critical data. The progression is diagnostic → data and authority map → read-only shadow → offline replay → supervised recommendation → bounded approval workflow → controlled pilot → a measured decision to scale or stop. Wyrd does not need access to live critical systems on day one, and proof and rollback are designed before anything runs.'},
    {t:'Governance and restraint',k:'governance ethics council accuser quarterly report restraint advisory oversight',s:'',l:'',p:'about.html#governance',pn:'About · governance',a:'Three standing functions: the High Advisory Council of Judgment and Restraint (multidisciplinary, advisory, not a launch veto), the Accuser\'s Office (attacks assumptions, ethics, feasibility and evidence, and recommends kill, repair or retest) and a quarterly State of AI and Restraint report including per-system self-assessments, minority views and unresolved risks.'},
    {t:'RASOS',k:'rasos deploy deployment update rollback repair revoke drift manifest lifecycle install',s:'arch',l:'Architecture defined',p:'platform.html',pn:'Platform · RASOS',a:'RASOS installs, updates, verifies, repairs, rolls back and revokes the stack across cloud, on-premise, edge, remote, air-gapped, intermittently connected, fleet and device environments — with signed manifests, package inspection, dependency verification, drift detection, staged rollout, offline bundles and post-deployment evidence. System-level wiring and production lifecycle proof remain.'},
    {t:'Restricted programs',k:'azrael lance restricted military defense offensive cyber palladium classified secret gated',s:'restricted',l:'Restricted',p:'corp-us.html',pn:'CORP-US division',a:'The restricted programs are named and placed on the CORP-US division page: Azrael (military-operations family), LANCE (licensed, authorized offensive-cyber, governed separately from WRAITH), PALLADIUM and Wyrd Dome (accountable counter-autonomy), and casualty-reduction intelligence. What may be described is lawful defense support, situational awareness, air-gapped coordination, logistics, resilient communications, operator protection and after-action proof. Operational content — targeting, weapons, kill-chain logic, offensive autonomy, intrusion or persistence methods — is not published in any Wyrd material at any tier, and is handled under lawful customer authority, licensing and export review.'},
    {t:'Visibility tiers',k:'visibility public partner private restricted nda access tier who can see',s:'',l:'',p:'restricted.html',pn:'Restricted register',a:'Four tiers. Public: main website, deck, recruiting, press. Partner: qualified design partners, regulated institutions, technical diligence. Private: investors, board, internal operating documents, controlled demonstrations. Restricted: authorized governmental, legal, security or defense channels only.'},
    {t:'Sustainability and cost',k:'sustainability energy watt efficiency cost cheap free green carbon compute',s:'',l:'',p:'platform.html#moats',pn:'Platform · why it compounds',a:'The claim is measurably efficient sovereign AI — more useful intelligence per watt, per euro and per external dependency — through model right-sizing, quantization, workload routing, caching, offline scheduling, hardware lifecycle management and lifecycle reporting. It is never "AI with no servers" or "zero-cost compute."'}
  ];

  var RESTRICTED=/(weapon|weapons|lethal|kill chain|kill-chain|targeting|target allocation|missile|munition|strike|firing|exploit|payload|intrusion|persistence|rootkit|sabotage|offensive cyber|lance|azrael|surveil|surveillance of|spy on|bypass|jam|countermeasure)/i;
  var CUSTOMERS=/(customer|client list|revenue|contract|who uses|case study|deployed at|reference)/i;

  function render(cards){ out.innerHTML=cards.join(''); }

  function card(item){
    var badge=item.l?'<span class="st '+item.s+'">'+item.l+'</span>':'';
    return '<div class="ans"><div class="ah"><h4>'+item.t+'</h4>'+badge+'</div><p>'+item.a+'</p>'+
      '<div class="cite"><span>Source: <a href="'+item.p+'">'+item.pn+'</a></span></div></div>';
  }

  function refusal(title,body){
    return '<div class="ans refuse"><div class="ah"><h4>'+title+'</h4><span class="st restricted">Not published</span></div><p>'+body+'</p>'+
      '<div class="cite"><span>Policy: <a href="about.html#language">About · language</a></span><span>Register: <a href="restricted.html">Restricted &amp; partner</a></span></div></div>';
  }

  function search(q){
    var terms=q.toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(function(w){ return w.length>2; });
    if(!terms.length) return [];
    return KB.map(function(item){
      var hay=(item.t+' '+item.k+' '+item.a).toLowerCase();
      var score=0;
      terms.forEach(function(t){
        if((item.t+' '+item.k).toLowerCase().indexOf(t)>-1) score+=3;
        else if(hay.indexOf(t)>-1) score+=1;
      });
      return {item:item,score:score};
    }).filter(function(r){ return r.score>0; }).sort(function(a,b){ return b.score-a.score; }).slice(0,3).map(function(r){ return r.item; });
  }

  function ask(q){
    q=(q||'').trim();
    if(!q){ out.innerHTML=''; return; }
    var cards=[];
    if(RESTRICTED.test(q)) cards.push(refusal('The program is listed. The operational detail is not.','Restricted programs are named and placed on the <a href="restricted.html">restricted &amp; partner register</a> — Azrael, LANCE, PALLADIUM, Wyrd Dome, casualty-reduction intelligence. What no Wyrd material publishes, at any tier, is the operational content: targeting, weapons, kill-chain logic, offensive autonomy, payloads, intrusion or persistence methods, countermeasure detail. Those require lawful customer authority, licensing and export review, and are handled only in authorized channels.'));
    if(CUSTOMERS.test(q)) cards.push(refusal('No customer, revenue or deployment claims','We do not publish customers, contracts, revenue, certifications or deployments that cannot be proved. What we can show is engineering evidence per system, with what it does not establish stated next to it.'));
    var hits=search(q);
    if(hits.length) cards=cards.concat(hits.map(card));
    else if(!cards.length) cards.push(refusal('No approved answer for that yet','Ask Wyrd only answers from an approved website knowledge base, and it will not invent capabilities. Try the platform, a division name, a product name, proof, research or pilots — or contact the Design Partner Office.'));
    render(cards);
  }

  form.addEventListener('submit',function(e){ e.preventDefault(); ask(input.value); });
  document.querySelectorAll('.suggest button').forEach(function(b){
    b.addEventListener('click',function(){ input.value=b.textContent; ask(b.textContent); });
  });
  ask('what is wyrd');
})();
